import { PGlite } from '@electric-sql/pglite';
import fs from 'fs';
const db = new PGlite(); const dir=new URL('../../supabase/migrations/', import.meta.url).pathname;
await db.exec(`create role anon nologin; create role authenticated nologin; create role service_role nologin; create schema auth; create table auth.users (id uuid primary key, email text, created_at timestamptz default now());
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
create function auth.jwt() returns jsonb language sql stable as $$ select jsonb_build_object('sub', current_setting('request.jwt.claim.sub', true), 'aal', 'aal2') $$;
grant usage on schema public, auth to anon, authenticated; grant execute on function auth.uid() to anon, authenticated;
alter default privileges in schema public grant all on tables to anon, authenticated; alter default privileges in schema public grant all on sequences to anon, authenticated;`);
for (const f of fs.readdirSync(dir).sort()) await db.exec(fs.readFileSync(dir+f,'utf8'));
console.log('applied', fs.readdirSync(dir).length);
const A='11111111-1111-1111-1111-111111111111';
await db.exec(`insert into auth.users (id) values ('${A}');`);
const as = async (sql) => { try { await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${A}',false);`); const r = await db.query(sql); return Object.values(r.rows[0] ?? {count:0})[0]; } catch(e){ return 'ERROR: '+e.message.split('\n')[0]; } finally { await db.exec('reset role'); } };
const rows = JSON.stringify([{from:5,to:6,date:'2025-08-01',airline:'JL'},{from:6,to:5,date:'2025-08-03'}]);
console.log('status (none):', JSON.stringify(await as('select public.plus_status()')));
console.log('import without plus:', await as(`select public.import_manual_flights('${rows}'::jsonb)`));
console.log('self-grant plus:', await as(`insert into subscriptions (user_id, status) values ('${A}','active')`));
await db.exec(`insert into subscriptions (user_id, status, current_period_end) values ('${A}','active', now() + interval '30 days')`);
console.log('status (active):', JSON.stringify(await as('select public.plus_status()')));
console.log('import with plus:', await as(`select public.import_manual_flights('${rows}'::jsonb)`));
console.log('bad row (same airport):', await as(`select public.import_manual_flights('[{"from":5,"to":5,"date":"2025-01-01"}]'::jsonb)`));
console.log('too many:', await as(`select public.import_manual_flights('${JSON.stringify(Array.from({length:501},()=>({from:5,to:6,date:'2025-01-01'})))}'::jsonb)`));
await db.exec(`update subscriptions set current_period_end = now() - interval '1 day'`);
console.log('expired -> import:', await as(`select public.import_manual_flights('${rows}'::jsonb)`));
console.log('manual rows:', (await db.query(`select count(*)::int n from manual_flights`)).rows[0].n);
