import { PGlite } from '@electric-sql/pglite';
import fs from 'fs';
const db = new PGlite(); const dir=new URL('../../supabase/migrations/', import.meta.url).pathname;
await db.exec(`create role anon nologin; create role authenticated nologin; create role service_role nologin; create schema auth; create table auth.users (id uuid primary key, email text, created_at timestamptz default now());
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
create function auth.jwt() returns jsonb language sql stable as $$ select jsonb_build_object('sub', current_setting('request.jwt.claim.sub', true), 'aal', 'aal2') $$;
grant usage on schema public, auth to anon, authenticated; grant execute on function auth.uid() to anon, authenticated;`);
for (const f of fs.readdirSync(dir).sort()) await db.exec(fs.readFileSync(dir+f,'utf8'));
console.log('applied', fs.readdirSync(dir).length);
const ADM='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', U='11111111-1111-1111-1111-111111111111';
await db.exec(`insert into auth.users (id, email) values ('${ADM}','admin@example.com'),('${U}','user@example.com');
 insert into ops.admins values ('${ADM}');
 insert into checkins (user_id, airport_id, lat, lon, accuracy_m, position_at, flags) values ('${U}',5,35.55,139.78,20,now(),'{}'),('${U}',6,42.77,141.69,20,now(),'{impossible_speed}'),('${U}',23,26.2,127.65,600,now(),'{low_accuracy,offline}');
 insert into flights (user_id, from_airport, to_airport, dep_checkin, arr_checkin, dep_at, arr_at, distance_km) values ('${U}',5,6,1,2,now()-interval '10 minutes',now(),820);`);
const as = async (uid, sql) => { try { await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${uid}',false);`); const r = await db.query(sql); return r.rows.length ? Object.values(r.rows[0])[0] : 'ok'; } catch(e){ return 'ERROR: '+e.message.split('\n')[0]; } finally { await db.exec('reset role'); } };
console.log('user is_admin:', await as(U, 'select public.is_admin()'), '| admin:', await as(ADM, 'select public.is_admin()'));
console.log('user stats:', await as(U, 'select public.admin_stats()'));
console.log('admin stats:', JSON.stringify(await as(ADM, 'select public.admin_stats()')));
const fl = await as(ADM, 'select public.admin_flagged(50)'); console.log('flagged:', fl.map(x => `${x.id}:${x.airport}:${x.flags}:${x.email}:${x.user_flagged}/${x.user_checkins}`));
console.log('user sees admins table:', await as(U, 'select count(*) from ops.admins'));
console.log('user void:', await as(U, 'select public.admin_void_checkin(2, \'test\')'));
console.log('admin clear 3:', await as(ADM, 'select public.admin_clear_flags(3)'));
console.log('admin void 2 (removes flight):', await as(ADM, "select public.admin_void_checkin(2, '位置偽装の疑い')"));
console.log('remaining checkins:', (await db.query('select id, flags from checkins order by id')).rows, '| flights:', (await db.query('select count(*)::int n from flights')).rows[0].n);
console.log('audit:', (await db.query('select action, target, detail from ops.admin_actions order by id')).rows.map(r=>`${r.action}:${r.target}:${r.detail ? r.detail.reason+'/'+r.detail.flights_removed : ''}`));
