import { PGlite } from '@electric-sql/pglite';
import fs from 'fs';
const db = new PGlite(); const dir=new URL('../../supabase/migrations/', import.meta.url).pathname;
await db.exec(`create role anon nologin; create role authenticated nologin; create role service_role nologin; create schema auth;
create table auth.users (id uuid primary key, email text, created_at timestamptz default now());
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb, '{}'::jsonb) $$;
grant usage on schema public, auth to anon, authenticated, service_role; grant execute on function auth.uid(), auth.jwt() to anon, authenticated, service_role;
alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant execute on functions to anon, authenticated, service_role;`);
for (const f of fs.readdirSync(dir).sort()) await db.exec(fs.readFileSync(dir+f,'utf8'));
console.log('applied', fs.readdirSync(dir).length);
const ADM='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', U='11111111-1111-1111-1111-111111111111';
await db.exec(`insert into auth.users (id, email) values ('${ADM}','a@x'),('${U}','u@x'); insert into ops.admins values ('${ADM}');`);
const as = async (role, uid, aal, sql) => { try { await db.exec(`set role ${role}; select set_config('request.jwt.claim.sub','${uid}',false); select set_config('request.jwt.claims','${JSON.stringify({sub:uid, aal})}',false);`); const r = await db.query(sql); return r.rows.length ? Object.values(r.rows[0])[0] : 'ok'; } catch(e){ return 'ERROR: '+e.message.split('\n')[0]; } finally { await db.exec('reset role'); } };
console.log('--- 分離');
console.log('anon reads ops.usage_events:', await as('anon','','', 'select count(*) from ops.usage_events'));
console.log('admin(aal2) reads ops.admins directly:', await as('authenticated',ADM,'aal2', 'select count(*) from ops.admins'));
console.log('public.usage_events still exists:', (await db.query(`select to_regclass('public.usage_events') as t`)).rows[0].t);
console.log('--- 2段階認証');
console.log('admin aal1 is_admin:', await as('authenticated',ADM,'aal1','select public.is_admin()'), '| registered:', await as('authenticated',ADM,'aal1','select public.admin_registered()'));
console.log('admin aal1 stats:', await as('authenticated',ADM,'aal1','select public.admin_stats()'));
console.log('admin aal2 stats ok:', typeof (await as('authenticated',ADM,'aal2','select public.admin_stats()')) === 'object');
console.log('admin aal2 metrics ok:', typeof (await as('authenticated',ADM,'aal2','select public.admin_metrics(7)')) === 'object');
console.log('user aal2 is_admin:', await as('authenticated',U,'aal2','select public.is_admin()'));
console.log('--- 回数制限');
const ev = JSON.stringify([{e:'tab',p:'x'}]);
const res=[]; for(let i=0;i<8;i++) res.push(await as('anon','','',`select public.log_events('sess00001', 'ios', 'v', '${ev}'::jsonb)`));
console.log('same session 8 calls in a minute:', res.join(','));
console.log('errors per session:', (await Promise.all(Array.from({length:12},(_,i)=>as('anon','','',`select public.log_error('sess00002','ios','v','js','e${i}',null)`)))).length, '→ stored', (await db.query(`select count(*)::int n from ops.client_errors where session='sess00002'`)).rows[0].n);
console.log('--- 非常停止');
console.log('app_status (anon):', JSON.stringify(await as('anon','','','select public.app_status()')));
console.log('user set flag:', await as('authenticated',U,'aal2',`select public.admin_set_flag('checkin_enabled','false'::jsonb)`));
console.log('admin set checkin off:', await as('authenticated',ADM,'aal2',`select public.admin_set_flag('checkin_enabled','false'::jsonb)`));
console.log('admin set bad flag:', await as('authenticated',ADM,'aal2',`select public.admin_set_flag('admin_mfa_required','false'::jsonb)`));
console.log('checkin_allowed (service):', await as('service_role','','','select public.checkin_allowed()'));
console.log('checkin_allowed (anon):', await as('anon','','','select public.checkin_allowed()'));
await as('authenticated',ADM,'aal2',`select public.admin_set_flag('logging_enabled','false'::jsonb)`);
console.log('logging off → log_events:', await as('anon','','',`select public.log_events('sess00003', 'ios', 'v', '${ev}'::jsonb)`));
console.log('log_rejection by anon:', await as('anon','','',`select public.log_rejection('out_of_range', 5, 2.1, 30, false)`));
console.log('rl_check by authenticated:', await as('authenticated',U,'aal1',`select public.rl_check('x', 1, 60)`));
console.log('rl_check by service:', await as('service_role','','',`select public.rl_check('checkin:u', 2, 60)`), await as('service_role','','',`select public.rl_check('checkin:u', 2, 60)`), await as('service_role','','',`select public.rl_check('checkin:u', 2, 60)`));
console.log('audit:', (await db.query('select action, target from ops.admin_actions order by id')).rows.map(r=>r.action+':'+r.target));
console.log('flagged list (aal2) ok:', Array.isArray(await as('authenticated',ADM,'aal2','select public.admin_flagged(10)')));
